### ISSUE TITLE
Add view for single applicant

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#13]
From the view showing list of applicants, add a keystroke that uses `input` to get a number for an applicant (in the list), and displays all the information for that single applicant.

e.g. after starting the program

```
Shortlist for test_role loaded:
6 applicants found
```

key 'a' shows list of applicants, numbered

```
1. Emma Jones
2. Marc Kolawole
3. Luis Ataei
4. Shahriar Perdigao
5. Sina Etemadi
6. Marie Brouard
```

key 'a' prompts for user to enter a number:

```
Applicant number? 
```

User enters a number to display full information about the applicant

```
Applicant number? 
1

1.Name: Emma Jones
CV Path: test_role/Emma_Jones_16743_Candidate_Pack.pdf
Scores: {}
```

**Comment by tamuri** [comment]
Any input that isn't a number of an applicant is ignored i.e. user remains in the list of all applicants view.

**Comment by shiyingwucl** [comment]
I've encountered an issue where after inputting the applicant number and getting the details of the applicant, it doesn't accept anymore
key press and is stuck on this screen: 
![Image](https://github.com/user-attachments/assets/7bf3f1c3-581c-4942-a52e-56eed61073f9)
