### ISSUE TITLE
Use pickle to save the shortlister into file

### ISSUE THREAD

**Issue by shiyingwucl** [UCL-ARC/shortlister#24]
### Definition of Done / Acceptance Criteria

Saves the following into a pickled file called shortlist:

Role
Criteria
Applicants: name plus individual applicant criteria marks

**Comment by tamuri** [comment]
Only the `Shortlist` instance needs to be pickled - all other parts of the model and referenced from there.

**Comment by tamuri** [comment]
Think about how you can check whether the saving procedure worked.
