### ISSUE TITLE
Adding simple unit tests

### ISSUE THREAD

**Issue by shiyingwucl** [UCL-ARC/shortlister#27]
Testing is being covered in the moodle course this week, so I thought it might be good practice for me to come up with simple test for shortlister. Where do you think would be a good place in my code to start testing?

**Comment by tamuri** [comment]
Yes, absolutely! You could start with writing tests for each of the `load_` functions.

By convention, tests are put in a directory called `tests` and each of the test files are named `test_???.py`. For example, you can put your tests in file called `test_model.py` and inside there put functions `test_load_role()`, `test_load_applicants()` etc.
