### ISSUE TITLE
Start the program, accepting a command-line argument for the role directory

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#3]
I would like to start the program on the command-line like this:

```
python main.py path/to/test_role
```

This will allow the program to work with several different roles.

The Python [argparse](https://docs.python.org/3/library/argparse.html) module will be useful to handle the arguments.

**Comment by shiyingwucl** [comment]
I've updated main.py to handle parsing in role directory as argument when running the file, parsing in an empty directory will result in FileNotFoundError, so maybe exception handling could be something to implement in the future?

**Comment by tamuri** [comment]
Yes, that's fine. You could check if the directory doesn't exist and print a nice message before using the argument.
