### ISSUE TITLE
Add "notes" field to Applicant

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#32]
Add a "note" field to applicant class (str type). Add ability to add arbritrary note to an applicant's record. We can assume that note will not be edited, but you can append a note to the existing note.

Something like:

```
Details for Emma Jones: 
CV Path: test_role/Emma_Jones_16743_Candidate_Pack.pdf
Scores:
[N]
> UCL grad.
Note: UCL grad.

[N]
> 3yrs AWS.

Note: UCL grad. 3yrs AWS
```

**Comment by shiyingwucl** [comment]
Should the notes field be a str type or a list of str?
