### ISSUE TITLE
Handle `Applicant` fields when empty

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#38]
When an `Applicant` has empty `scores` or `notes`, output `No scores` and `No notes`, respectively.

**Comment by shiyingwucl** [comment]
I'm thinking of adding two if and else checks within view.py to check if  scores or notes are empty:

```python
if applicant.scores == {}:
    print("No scores")
else:
    for criterion, score in applicant.scores.items():
    print(f"{criterion.name:^20}: {score:^20}")
```

I do feel that doing this twice makes the function less clean - what do you think?

**Comment by tamuri** [comment]
I think you'll need the two check - no way around that.
