### ISSUE TITLE
List scored `Criterion` for applicant in the same order as criteria of role

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#41]
An applicant's scores are currently listed in the order they were added to the applicant. This doesn't necessarily match the order of the criteria as listed for the role i.e. the order presented in criteria.csv.

We want to print applicants' scores in the same order as stored in `Role.criteria`.

Example: I scored this applicant's criteria in non-sequential order, so they are printed differently to the criteria for test_role

```
Details for Joe Bloggs:
CV Path: test_role/Joe_Bloggs_152827_Candidate_Pack.pdf
Scores:
        PhD         :      Excellent
   Best practices   :       Moderate
 Research software  :     Satisfactory

Notes:

The criteria for test_role are:

0. PhD: Degree or relevant experience
1. Research software: Authorship,development and maintenance
2. Best practices: Issue tracking, testing, documentation etc.
```

**Comment by shiyingwucl** [comment]
Should I sort the dictionary with in the update_applicant_score function inside model? Or would it be better to write a separate function for it?

Currently it is looking like this which feels very long and hard to understand:

```python
self.applicant(self.applicant_index).scores = {key: self.applicant(self.applicant_index).scores[key] for key in self.shortlist.role.criteria if key in self.applicant(self.applicant_index).scores}        
```

**Comment by shiyingwucl** [comment]
Ah I see, so I just need to change the way it is printed in view?
