### ISSUE TITLE
Allow sorting of applicants

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#43]
On the applicant list view, user can sort applicants:

- Alphabetically, the default. Need to make sure the files retrieved by `glob` are sorted on load.
- By total score, both descending & ascending options. 
    - Equal scoring applicants are sorted alphabetically. 
    - Candidates with no scores at all are "less than" candidates with score of zero.

Sorts the list in-place using the `.sort()` method rather than `sorted()`.

Keystroke: S (activate sorting options)
a - a[lphabetical]
s - s[cores ascending]
d - [scores ]d[escending]

**Comment by shiyingwucl** [comment]
Is it correct to put the sort functions inside model? I found if I put it in model, I can't update the keypress options after sorting the list.

**Comment by tamuri** [comment]
Fine for the sorting of applicants can go in `model.py`. The "handler" of the keypress is always in the controller, and the controller communicates with the model and view to do the right thing for the keypress.

**Comment by shiyingwucl** [comment]
If I put sort into a single function, when I display the key binds for sort with "?", the docstrings all point to the sort function so it ends up being not very helpful:
```
Entering sorting mode

---List of shortcuts---
q: Exit the program
a: Activates sort
s: Activates sort
d: Activates sort
```
How could I display the docstring of the actual sort function in model?

**Comment by tamuri** [comment]
> EDIT: I realised Issue https://github.com/UCL-ARC/shortlister/issues/49 already talks about this problem😅

Yes, exactly! Don't worry about it for now.
