### ISSUE TITLE
Evaluate packages that extract text from PDF files

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#45]
There is some information stored in an applicant's PDF we would like access to. For example, we would like to get their name and visa requirements. This is part of the standard output from the Talentlink recruitment candidate pack. And be able to search for keywords and phrases in an applicant's CV + cover letter. 

First step is to evaluate Python packages that extract text from PDFs. I found two that are widely used and actively maintained, with lots of tutorials and examples: [PyMuPDF](https://github.com/pymupdf/pymupdf) and [pypdf](https://github.com/pymupdf/pymupdf)

Evaluation:

- Get several real candidate packs from Talentlink (will need to be anonymised)
- Write code to extract the text for each of the libraries
- Rank simplicity of code, access to documentation/examples, performance
- Rank how well extracted text preserves the layout of the original PDF

**Comment by shiyingwucl** [comment]
I've looked at these three packages so far:
#### PyMuPDF:
The format extracted text is still intact and readable, although bullet points are slightly skewered:
![Image](https://github.com/user-attachments/assets/5a93164e-113d-429c-afad-707652523914)

#### PyPDF:
- No format and some error message : ![Image](https://github.com/user-attachments/assets/326623c3-7c92-4036-b428-345b1294320b)

#### PDFplumber:
Almost exact to PyMuPDF, but handles bullet points better
![Image](https://github.com/user-attachments/assets/8a5b401c-b52d-400d-9956-dc52ccf579ad)

**Comment by tamuri** [comment]
PDFplumber looks good. Here are the test CVs with the cover page as supplied by the Talentlink website.

[Emma_Jones_16743_Candidate_Pack.pdf](https://github.com/user-attachments/files/17773265/Emma_Jones_16743_Candidate_Pack.pdf)
[Sarah_Thompson_82376_Candidate_Pack.pdf](https://github.com/user-attachments/files/17773268/Sarah_Thompson_82376_Candidate_Pack.pdf)
[Michael_Davis_89763_Candidate_Pack.pdf](https://github.com/user-attachments/files/17773272/Michael_Davis_89763_Candidate_Pack.pdf)

See how successfully you can pull out the name, email address, contact details and visa requirements from the cover page (always page one in the candidate pack)
