### ISSUE TITLE
Get several real anonymised candidate packs from Talentlink

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#46]
The Talentlink candidate packs contain forms from which we can extract useful information. Packs will need to be anonymised, and not shared publically i.e. not added to the repo

**Comment by tamuri** [comment]
I think it will be too difficult to anonymise a real candidate pack. But I have copied the Talentlink cover sheet and will add to the existing test PDFs.

**Comment by shiyingwucl** [comment]
Could the pdf files be updated again please? I tried to reopen the branch and cherry pick but it shows that there is no changes.
