### ISSUE TITLE
Add option to clear score for applicant

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#48]
When adding score to applicant, add an option in addition to Unsatisfactory, Moderate etc. to clear/remove the selected score from the applicant's scores.

Example:

```
The criteria for test_role are:

0. PhD: Degree or relevant experience
1. Research software: Authorship,development and maintenance
2. Best practices: Issue tracking, testing, documentation etc.

You selected PhD. Select the score you want to change to:

0: Unsatisfactory
1: Moderate
2: Satisfactory
3: Excellent
c: clear score
```

**Comment by shiyingwucl** [comment]
Should I make it so that when the selected criterion isn't marked yet, the clear score option doesn't show?
