### ISSUE TITLE
Add filtering of applicant list

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#50]
(Need to think about this a bit more before starting...)

When viewing list of applicants, allow users to filter (or search) the list and only display applicants matching the specified filter.

The controller will need to break the coupling between `self.shortlist.applicants` and the applicant list we view. We could add a field `self.selected_applicants: List[Applicant]`. On start, this field points to the full list of applicants. Filtering will overwrite this field by finding matching applicants in the full list (i.e. `self.shortlist.applicants`) and adding them to the `self.selected_applicants` list.

There are, in principle, many ways we would want to filter the applicant list (different operations on applicants' names, scores, notes).

In the first iteration of this functionality, we could allow the user to write a Python condition that we would use to filter the list using [`eval`](https://docs.python.org/3/library/functions.html#eval). For example:

```
Enter your filter: 'Emma' in a.name 
```

We would take this input a get the matching applicants using:

```python
self.selected_applicants = eval(f"[a for a in self.shortlist.applicants if {filter}]")
```

i.e. `eval()` would execute `[a for a in self.shortlist.applicants if 'Emma' in a.name]` and put the result in `self.selected_applicants`

There should be a command to clear the filter.

**Comment by shiyingwucl** [comment]
Rather than using eval(), maybe we could have some applicant attribute we can select from, and then input some keywords? I was thinking it might be difficult to use if you have to write code to filter out applicants.

**Comment by shiyingwucl** [comment]
I attempted to write a helper function: name(), which just concatenates" in applicant.name" to a string, but I can't really grasp how eval works due to the following:
```
# my function: name("Davis") which returns string "'Davis' in applicant.name"
[applicant for applicant in self.shortlist.applicants if name("Davis")] # string that is evaluated

# my result - no changes after applying the filter
1. Emma Jones
2. Michael Davis
3. Sarah Thompson
```

**Comment by tamuri** [comment]
I think it might be easier to let the user know that the variable `applicant` needs to be passed to the function, and write the functions accordingly. ie `name(applicant, "Emma")` and the function returns True or False.

Then you don't need double eval, which I think will be a bit fragile.

**Comment by shiyingwucl** [comment]
Like this?:
```python
def name(applicant, name:str):
    if name in applicant.name:
        return True
```

**Comment by tamuri** [comment]
Yes, although you also need to handle the case when `False`. I'd write it like this:

```python
def name(applicant: Applicant, name:str):
    return name in applicant.name
```
