### ISSUE TITLE
Adjustments to the table of applicants

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#65]
Pressing `a` at the home screen brings up list of applicants.
Pressing `t` shows table of applicants with ranked criteria

Define a variable for the selected applicants' view, which would be "list" when the program starts.

`t` will display _and_ toggle the selected applicants' view, switching between list and table.

So, when going the applicant's screen (either `a` from the home view, or `q` from applicant detail view), the applicants are displayed using the currently selected view: "list" or "table".

Other changes:

- Truncate names if longer than 15 characters and add ellipses
- Use ASCII middle dot character instead of hyphen for empty cell in table

**Comment by shiyingwucl** [comment]
When truncating the applicant names, how many characters/words should be displayed before omitting the rest with ellipses?

**Comment by tamuri** [comment]
Show 15 characters, truncate the rest.
