### ISSUE TITLE
Allow the user to compare candidates pairwise and record the results

### ISSUE THREAD

**Issue by tamuri** [UCL-ARC/shortlister#69]
The tool will run a "tournament" where applicants are compared in pairs, and the results of the comparisons are used to determine overall ranking.

1. Take a list of applicants
2. Conduct pairwise comparisons between applicants
3. Rank applicants based on the comparisons

### Step 1: Implement pairwise comparison logic

This should be a separate module (e.g. `tournament.py`) that can do the comparisons on any object (e.g. any items in a list). Don't design it specifically for the shortlister model or applicants.

Build the logic:

- Accept a list of things to compare
- Display a pair to the user
  - Create a function to generate pairs to compare
- Ask users the select the better one by typing a number or letter
- Store the results
  - Add functionality to capture and store the user's input for each pair
  - Results a saved in a format that can be looked at later
      - Print to screen, save to file
      - Allow user to save and resume comparisons

### Step 2: Ranking algorithm

- Research and choose a suitable ranking method
- Write a function to process the results from step 1 and calculate the ranking
- Display the ranking to the user
- Save the ranking to file

### Step 3: Integrate into shortlister tool

- Allow user to send selected applicants to compete in tournament
- Capture the ranking after the process

**Comment by shiyingwucl** [comment]
A few questions after I started to outline the code:

- What format would the data come from and in what format?
-

**Comment by tamuri** [comment]
> What format would the data come in? (considering its not specifically for the shortlister)

A list of items, you don't know what they are, but they are printable: e.g. `[682, 619, 807, 161]` or `["lorem", "ipsum", "dolor"]`

> Should there be any conditions when generating the pair, or just randomly?

You need a system such that you can do the ranking - what are the options? While random is okay, you could end up getting the same pair to rank.

**Comment by tamuri** [comment]
Addition: we can assume that the input list has some kind of preliminary order that we are looking to refine. That might influence the logic to generate the pairs.
